name: Build macOS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [arm64, x64]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci

      - run: npx electron-forge make --platform=darwin --arch=${{ matrix.arch }}

      - uses: actions/upload-artifact@v4
        with:
          name: Songsta-mac-${{ matrix.arch }}
          path: |
            out/make/zip/darwin/${{ matrix.arch }}/*.zip
            out/make/dmg/darwin/${{ matrix.arch }}/*.dmg